### ISSUE TITLE
Who has the design documentation for peergos? 

### ISSUE THREAD

**Issue by Nikola1Tesla** [Peergos/web-ui#177]
Hello,everyone! I am a programmer, now I am working on the peergos project.But there is no design document for peergos, which makes it very difficult to understand the project. Who has relevant design documents, can you help to send me one?

**Comment by ianopolous** [comment]
What are you planning on doing? The overall design is described in https://book.peergos.org
However the most detail is in comments in the code itself.

**Comment by Nikola1Tesla** [comment]
thank you very much! I want to learn the code of peergos.The overall design is too rough and not detailed enough. There are also fewer comments on the code. I want a more detailed design document.Are you?
