### ISSUE TITLE
latest release, v0.12.0, missing Peergos.jar

### ISSUE THREAD

**Issue by jahway603** [Peergos/web-ui#470]
The latest release, v0.12.0, is missing Peergos.jar.

**Comment by ianopolous** [comment]
There's a link to the binaries in the release.

**Comment by jahway603** [comment]
@ianopolous how would you suggest I script this since `wget https://peergos.net/public/peergos/releases/v0.12.0/java/Peergos.jar` does not function correctly?

I'm trying to update the Arch Linux AUR package to the latest Peergos by sourcing Peergos.jar as [seen here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=peergos#n13). Any suggestions as to how I can source Peergos.jar from "Download binaries from https://peergos.net/public/peergos/releases link" so that I can make a reproducible PKGBUILD on Arch (as [I've been doing since v 0.8.0](https://aur.archlinux.org/cgit/aur.git/?h=peergos))?

A related issue is https://github.com/Peergos/web-ui/issues/382 where Peergos.jar was missing from v 0.9.0.

**Comment by ianopolous** [comment]
As long as you're okay with github being able to modify the jar then I can mirror it in the release here. Older versions should not be run.

**Comment by jahway603** [comment]
Thank you @ianopolous

There is a 2nd Arch AUR package that builds using ant dist, [as seen here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=peergos-git#n26). I have provided two packages so users have a choice.
